pipeline {
    agent any
    tools {
        maven 'maven-3.6.3'
    }
    environment {
        DATE = new Date().format('yy.MM')
        TAG = "${DATE}.${BUILD_NUMBER}"
        DOCKERHUB_CREDENTIALS = credentials('juanbrnyjfrogregistry')
    }
    stages {
        stage ('Download code from main branch') {
	  steps {
	    git branch: 'main', url: 'https://github.com/juanbrny/spring-petclinic.git'
	  }
        }
        stage ('Compile and Test') {
            steps {
              sh 'mvn test'
            }
        }
	stage ('Compile and Package') {
            steps {
              sh 'mvn package'
            }
        }
        stage('Docker Build Container') {
            steps {
                script {
		  sh "docker build -f docker/Dockerfile --build-arg ARTIFACT_NAME=spring-petclinic-2.6.0-SNAPSHOT -t spring-petclinic:${TAG} ."
                }
            }
        }
        stage('Container Registry Login') {
            steps {
              sh 'echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin juanbrny.jfrog.io'
            }
        }
        stage('Image publish to Container Registry') {
            steps {
              sh 'docker image tag spring-petclinic:${TAG} juanbrny.jfrog.io/default-docker-virtual/spring-petclinic:${TAG}'
              sh 'docker push juanbrny.jfrog.io/default-docker-virtual/spring-petclinic:${TAG}'
          
              sh 'docker image tag spring-petclinic:${TAG} juanbrny.jfrog.io/default-docker-virtual/spring-petclinic:latest'
              sh 'docker push juanbrny.jfrog.io/default-docker-virtual/spring-petclinic:latest'
            }
        }        
    }
    post {
      always {
        sh 'docker logout'
      }
    }
}
